version: '3.7'
services:
  mysql:
    cap_add:
      - SYS_NICE
    container_name: concert-msa-mysql
    image: ubuntu/mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - 23306:3306
    environment:
      - MYSQL_USER=abcd
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./mysql-config:/etc/mysql/conf.d  # Mount the custom configuration file
      - ./mysql-logs:/var/log  # Mount the custom configuration file